name: Hello World Python

on:
  push:
    branches:
      - main


jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Hello World script
      run: python app.py
    - name: Virtual env
      run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Deploy Flask Application
      run: |
          nohup python3 app.py 
    




      
      
          
   
          
     
