name: Deploy Flask App

on:
  push:
    branches:
      - main

env:
  HEALTHCHECK_URL: http://13.203.197.210:5000

jobs:
  Build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Virtual env
        run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          
      - name: Deploy Flask Application
        run: |
          nohup python3 app.py &

  health:
    needs: Build-test-deploy
    runs-on: self-hosted

    steps:
      - name: Health check
        run: |
          for i in {1..10}; do
            curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service...";
            sleep 5;
